### ISSUE TITLE
Issue with Gaussian and Gamma reconstruction cost

### ISSUE THREAD

**Issue by xiniyiwang** [arsedler9/lfads-torch#23]
Hi Andrew,
I can successfully run the multisession script with Poisson cost. However, I have a problem using Gamma reconstruction cost with calcium imaging dataset. This issue also occurs when I use Gaussian reconstruction. 
When I set:

reconstruction:
target: lfads_torch.modules.recons.MultisessionReconstruction
datafile_pattern: ${datamodule.datafile_pattern}
recon:
target: lfads_torch.modules.recons.Gamma

there is an error in line 367, lfads-torch/model: 'batch[s].recon_data' has a shape of [21, 25, 92], but 'output[s].output_params' has a shape of [21, 25, 46, 2].
where 21 is the number of valid trials, 25 is time steps, and 92 is the neuron numbers.
Since Gamma and Gaussian reconstruction need two parameters, the dataset will be divided into two parts. However, in lfads-torch code, the divided dataset is not reshaped to be the original size when calculating loss. Is this the reason why this issue occurs?

Is there anything else I need to do after setting 'target' as 'lfads_torch.modules.recons.Gamma'?
I'd appreciate it if you could give me some advice.
Thanks!

**Comment by arsedler9** [comment]
Hey @xiniyiwang, in addition to setting the `reconstruction._target_` to one of the objects in `recons`, you'll need to set `readout` to the following:
```
readout:
  _target_: torch.nn.ModuleList
  modules:
    - _target_: lfads_torch.modules.readin_readout.FanInLinear
      in_features: ${model.fac_dim}
      out_features: 184 # 92 neurons x 2 params
```
You might also find it helpful to replace `CoordinatedDropout` with `TemporalShift` in the `train_aug_stack` for Gamma observations (more detail in [the paper](https://iopscience.iop.org/article/10.1088/1741-2552/ac6369)). Hope that helps!

**Comment by arsedler9** [comment]
Ahh, actually if you're using `MultisessionReadout`, it will infer the number of output features from your data files, so we'll need to add an `n_params` argument to that object depending on your `recon`.

**Comment by xiniyiwang** [comment]
Thanks for your advice. The error as mentioned earlier didn't happen now. However, when I set `readout` as:
```
readout:
  _target_: lfads_torch.modules.readin_readout.MultisessionReadout
  datafile_pattern: ${datamodule.datafile_pattern}
  in_features: ${model.fac_dim}
  pcr_init: False
  recon_params: 2
```

and `train_aug_stack`:
```
train_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.modules.augmentations.TemporalShift #CoordinatedDropout 
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
```

and:
```
reconstruction:
  _target_: lfads_torch.modules.recons.MultisessionReconstruction
  datafile_pattern: ${datamodule.datafile_pattern}
  recon:
    _target_: lfads_torch.modules.recons.Gamma
variational: True
co_prior:
  _target_: lfads_torch.modules.priors.AutoregressiveMultivariateNormal
  tau: 10.0
  nvar: 0.1
  shape: ${model.co_dim}
ic_prior:
  _target_: lfads_torch.modules.priors.MultivariateNormal
  mean: 0
  variance: 0.1
  shape: ${model.ic_dim}
ic_post_var_min: 1.0e-4
```

1. The above settings will lead to an error:
```
ray.exceptions.RayTaskError(InstantiationException): ray::ImplicitFunc.train() (pid=2766465, ip=192.168.1.102, repr=run_model)
  File "/home/datadisk1/wxy/lfads-torch/lfads_torch/modules/augmentations.py", line 25, in __init__
    assert all([hasattr(t, "process_losses") for t in self.loss_transforms])
AssertionError
```

2. When I use `CoordinatedDropout` instead:
```
train_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.modules.augmentations.CoordinatedDropout #TemporalShift
      cd_rate: 0.3 # sampled
      cd_pass_rate: 0.0
      ic_enc_seq_len: ${model.ic_enc_seq_len}
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.modules.augmentations.AugmentationStack
```
another error occurs:
```
  File "/home/datadisk1/wxy/lfads-torch/lfads_torch/model.py", line 492, in training_step
    return self._shared_step(batch, batch_idx, "train")
  File "/home/datadisk1/wxy/lfads-torch/lfads_torch/model.py", line 362, in _shared_step
    output = self.forward(
  File "/home/datadisk1/wxy/lfads-torch/lfads_torch/model.py", line 236, in forward
    ic_post = self.ic_prior.make_posterior(ic_mean, ic_std)
  File "/home/datadisk1/wxy/lfads-torch/lfads_torch/modules/priors.py", line 30, in make_posterior
    return Independent(Normal(post_mean, post_std), 1)
  File "/home/datadisk/wxy/Anaconda/envs/lfads-torch/lib/python3.9/site-packages/torch/distributions/normal.py", line 56, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/datadisk/wxy/Anaconda/envs/lfads-torch/lib/python3.9/site-packages/torch/distributions/distribution.py", line 56, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (40, 100)) of distribution Normal(loc: torch.Size([40, 100]), scale: torch.Size([40, 100])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<SplitBackward0>)
```
Is there any step or parameter I didn't set up correctly?

**Comment by arsedler9** [comment]
Thanks for reporting this @xiniyiwang. I looked into it and it looks we didn't have `process_losses` implemented for `TemporalShift`, which was causing the first error. I just merged PR #25 which should fix this issue. The NaNs you're seeing with `CoordinatedDropout` are likely an optimization failure, so I would recommend reducing the learning rate.

**Comment by xiniyiwang** [comment]
The first error is fixed using the new code. 
However, the NaNs also exist immediately, even if I set the learning rate to 1e-7. Based on my understanding, maybe the (batch_size, seq_len or dim) of (ic, ci or co), should match each other?
Here are my settings:
```
 --------- architecture --------- #
encod_data_dim: 30
encod_seq_len: 37
recon_seq_len: ${model.encod_seq_len}
ext_input_dim: 0
ic_enc_seq_len: 0
ic_enc_dim: 32
ci_enc_dim: 32
ci_lag: 1
con_dim: 32
co_dim: 4
ic_dim: 32
gen_dim: 100
fac_dim: 30
```
and:
`batch_size=100`

**Comment by arsedler9** [comment]
This is with the Gamma distribution, right? Is your data in the range (0, inf)?

**Comment by xiniyiwang** [comment]
Yes, it's Gamma distribution. 
There are many "0"s in my data. But no negative numbers and inf/NaN.

**Comment by arsedler9** [comment]
Ahh, that's the issue. Zeros are not in the support of the Gamma distribution. I just looked back at the original issue where you mentioned that this is calcium imaging data. The model you want is the `ZeroInflatedGamma` distribution, implemented [here](https://github.com/arsedler9/lfads-torch/blob/6f58d249e1334c272146938aa1b3b27686580588/lfads_torch/modules/recons.py#L133). This model is described in [this paper](https://www.nature.com/articles/s41593-022-01189-0). I think there were some changes in that paper that haven't made it into this implementation yet, mainly channel-wise dropout. @fzhu23, your main innovations were ZIG and channel-wise dropout, correct?

**Comment by xiniyiwang** [comment]
Oh, that's my oversight. Maybe I should try both lfads-torch and RADICaL for comparison.

**Comment by arsedler9** [comment]
That seems reasonable--you can find a link to the RADICaL code in that paper. If you use `ZeroInflatedGamma` recon and `SelectiveBackpropThruTime` augmentation with `lfads-torch`, it should be the same, but it hasn't been tested as extensively as the rest of the code base. If you aren't trying to upsample your data, then you probably don't need to use SBTT.

**Comment by xiniyiwang** [comment]
Thanks for your very kind reply. But a new error with `ZeroInflatedGamma` happened so I reopened this issue. 
Now I use `ZeroInflatedGamma` recon:
```
# --------- priors / posteriors --------- #
reconstruction:
  _target_: lfads_torch.modules.recons.MultisessionReconstruction
  datafile_pattern: ${datamodule.datafile_pattern}
  recon:
    _target_: lfads_torch.modules.recons.ZeroInflatedGamma #Gaussian #
variational: True
co_prior:
  _target_: lfads_torch.modules.priors.AutoregressiveMultivariateNormal
  tau: 10.0
  nvar: 0.1
  shape: ${model.co_dim}
ic_prior:
  _target_: lfads_torch.modules.priors.MultivariateNormal
  mean: 0
  variance: 0.1
  shape: ${model.ic_dim}
ic_post_var_min: 1.0e-4
```
```
readout:
  _target_: lfads_torch.modules.readin_readout.MultisessionReadout
  datafile_pattern: ${datamodule.datafile_pattern}
  in_features: ${model.fac_dim}
  pcr_init: False
  recon_params: 3
```
 and there exists a new error:
```
2024-09-21 20:54:49,058 ERROR trial_runner.py:993 -- Trial run_model_aa636_00000: Error processing event.
ray.exceptions.RayTaskError(InstantiationException): ray::ImplicitFunc.train() (pid=176695, ip=192.168.1.102, repr=run_model)
TypeError: __init__() missing 5 required positional arguments: 'recon_dim', 'gamma_loc', 'scale_init', 'scale_prior', and 'scale_penalty'
```
I looked into the code and in `class ZeroInflatedGamma`, I found there is a "TODO":
```
class ZeroInflatedGamma(nn.Module, Reconstruction):
    def __init__(
        self,
        recon_dim: int,  # TODO: Fix for multisession
        gamma_loc: float,
        scale_init: float,
        scale_prior: float,
        scale_penalty: float,
    ):
```
Is there anything that needs to be further fixed?

**Comment by arsedler9** [comment]
@xiniyiwang I'm glad you got it working! Not sure what you ended up doing, but the `TODO` is just a reminder to implement automatic inference of the `recon_dim` from the data files for `MultisessionReconstruction`, sort of like the `MultisessionReadin/Readout` implementation [here](https://github.com/arsedler9/lfads-torch/blob/6f58d249e1334c272146938aa1b3b27686580588/lfads_torch/modules/readin_readout.py#L37). You'll just need to pass in an `nn.ModuleList` of `ZeroInflatedGamma` in the config with the appropriate `recon_dims` in your data.

**Comment by xiniyiwang** [comment]
I just passed the 5 parameters:
```
reconstruction:
  _target_: lfads_torch.modules.recons.MultisessionReconstruction
  datafile_pattern: ${datamodule.datafile_pattern}
  recon:
    _target_: lfads_torch.modules.recons.ZeroInflatedGamma #Gaussian #
    recon_dim: 86
    gamma_loc: 0
    scale_init: 1.0
    scale_prior: 0.01
    scale_penalty: 0.01
```
and then it works. 
I found that `gamma_loc` must be zero, other values `{5, 10, or 50}` will lead to negative numbers and errors.
Are there any principles for setting these parameters? What do these parameters depend on?

**Comment by arsedler9** [comment]
I'd recommend starting with the parameters used in [the RADICaL paper](https://pubmed.ncbi.nlm.nih.gov/36424431/) (see below). That paper is probably the best place to look for guidance on setting the parameters. You may also want to reach out to those authors for more assistance.
```
reconstruction:
  _target_: lfads_torch.modules.recons.MultisessionReconstruction
  datafile_pattern: ${datamodule.datafile_pattern}
  recon:
    _target_: lfads_torch.modules.recons.ZeroInflatedGamma #Gaussian #
    recon_dim: 86
    gamma_loc: 0.1
    scale_init: 20.0
    scale_prior: 20.0
    scale_penalty: 1e-4
```
